import streamlit as st
import joblib
import pandas as pd

# Load trained model
model = joblib.load("models/linear_regression_medical_insurance_default.sav")

# App configuration
st.set_page_config(
    page_title="Medical Insurance Cost Predictor",
    page_icon="💰",
    layout="centered"
)

# App title and description
st.title("💰 Medical Insurance Cost Predictor")

st.write(
    "This application estimates medical insurance charges based on patient information. "
    "The prediction is generated using a Linear Regression model trained on medical insurance data."
)

st.divider()

# User input section
st.subheader("Patient information")

age = st.slider("Age", min_value=18, max_value=100, value=30)

sex = st.selectbox("Sex", ["male", "female"])

bmi = st.slider("BMI", min_value=10.0, max_value=50.0, value=25.0, step=0.1)

children = st.slider("Number of children", min_value=0, max_value=10, value=0)

smoker = st.selectbox("Smoker", ["yes", "no"])

region = st.selectbox(
    "Region",
    ["southwest", "southeast", "northwest", "northeast"]
)

# Convert categorical inputs into the same encoded format used during training
sex_male = 1 if sex == "male" else 0
smoker_yes = 1 if smoker == "yes" else 0

region_northwest = 1 if region == "northwest" else 0
region_southeast = 1 if region == "southeast" else 0
region_southwest = 1 if region == "southwest" else 0

# Create input dataframe with the same columns and order used to train the model
input_data = pd.DataFrame([[
    age,
    bmi,
    children,
    sex_male,
    smoker_yes,
    region_northwest,
    region_southeast,
    region_southwest
]], columns=[
    "age",
    "bmi",
    "children",
    "sex_male",
    "smoker_yes",
    "region_northwest",
    "region_southeast",
    "region_southwest"
])

st.divider()

# Prediction section
if st.button("Predict Insurance Cost"):
    prediction = model.predict(input_data)[0]

    st.success(f"Estimated insurance cost: ${prediction:,.2f}")

    st.caption(
        "Note: This result is an estimate generated by a Machine Learning model "
        "and should not be interpreted as a real insurance quote."
    )